openapi: 3.0.0
info:
  title: Pokemon
  version: v2
servers:
  - url: 'https://pokeapi.co/api/v2/'
paths:
  /pokemon/{Name}:
    get:
      summary: 'Getting a Pokemon'
      description: 'Get details for a pokemon'
      parameters:
        - in: path
          name: Name
          schema:
            type: string
          example: 'Ditto'  
          required: true      
      responses:
        200:
          description: 'Succesful Response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
        404:
          description: 'Not found response'
          content:
            text/plain:
              schema:
                type: 'string'
                example: Not Found
components:
  schemas: 
    Pokemon:
      type: object
      description: 'Pokemon information'
      properties:
        Id:
          type: number
          description: 'Identifier'
          example: 132
        Name:
          type: string
          description: 'Name'
          example: 'Ditto'
        Height:
          type: number
          description: 'Height in feet'
          example: 3
        Weight:
          type: number
          description: 'Weight in pounds'
          example: 40
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
